src/core/eko.ts, src/models/action.ts, src/models/workflow.ts, src/schemas/workflow.schema.ts, src/services/parser/workflow-parser.ts, src/types/action.types.ts, src/types/workflow.types.ts, src/utils/execution-logger.ts, test/integration/workflow.execution.test.ts, test/integration/workflow.generation-and-execution.test.ts, test/unit/action.test.ts, test/unit/workflow-parser.test.ts, test/unit/workflow.test.ts
This pull request introduces several enhancements and optimizations to the workflow execution process. Key changes include reducing the number of `write_context` tool calls, adding the ability of reusing tool output as subtask output, streamlining node IO handling, and integrating an execution logger within actions.
These changes are required to improve the efficiency and clarity of workflow executions. By optimizing input/output handling and adding logging capabilities, we aim to enhance both performance and traceability. This addresses internal optimization goals and improves developer experience.
Workflow DSL updated. In the new version, only output (but not input) is included in a subtask specification. At run time, input is automatically gathered from the outputs of dependent nodes.
=> Execution Optimization and Logging Enhancements

src/index.ts, src/models/action.ts, src/models/workflow.ts, src/services/parser/workflow-parser.ts, src/services/workflow/generator.ts, src/types/workflow.types.ts, src/utils/execution-logger.ts
This pull request introduces improvements to the logging system by adding support for logging images and capturing the last message array on errors. These enhancements aim to provide more detailed and useful logging information.
The changes are required to improve the debugging process by providing more context in logs, especially when errors occur. This enhancement addresses the need for better traceability and debugging capabilities.
- Developers can now inject their own ExecutionLogger with customized options to the workflow executor, useful for frontend development
- In a nodejs environment, an option for saving screenshots to files is provided, facilitating research/benchmarking
None.
These changes are backward-compatible and should not affect existing functionality.
=> Enhance Logging with Image Support and Error Details

src/extension/tools/tab_management.ts, src/models/action.ts, src/nodejs/tools/browser_use.ts, src/types/tools.types.ts
This pull request addresses issues with image handling and enhances logging capabilities. It includes a fix to prevent images from being misinterpreted as text and improvements to the execution logger to support image logging.
The changes are necessary to ensure images are processed correctly and to improve logging for better error tracking and debugging. This resolves issues with image misinterpretation and enhances the logging system to provide more detailed information.
None.
N/A
=> Fix Image Handling and Logging Enhancements

src/core/eko.ts, src/models/action.ts, src/models/workflow.ts, src/types/action.types.ts, src/types/workflow.types.ts
Add `eko.cancel()` function to support cancel workflow execution.
=> Feat: Support Cancel Workflow Execution

src/extension/tools/export_file.ts, src/extension/tools/open_url.ts, src/extension/tools/tab_management.ts, src/extension/tools/web_search.ts, src/types/workflow.types.ts
Add `onTabCreated` callback function.
=> Feature: Add onTabCreated callback

src/extension/tools/browser.ts, src/extension/tools/browser_use.ts, src/extension/utils.ts, src/types/workflow.types.ts, src/universal_tools/human.ts
Refactored the browser.ts and browser_use.ts files to include better error handling and more descriptive logging for debugging purposes. Added checks and try-catch blocks to ensure reliability and easier troubleshooting of the extension's functionality.
This change may be helpful for troubleshooting future minor issues with browser use, like #38 .
=> refactor(extension): improve error handling and logging

rollup.config.js, src/web/tools/index.ts
这个 PR 修复了 web 环境运行报错 workflow contains undefined tools
原因：web/tools 模块没有添加 universal_tools
Closes https://github.com/FellouAI/eko/issues/54
=> fix: workflow contains undefined tools

src/universal_tools/summary_workflow.ts
这个 PR 微调了`summary_workflow`的`descriptoin`，以便让 Eko 总结这个工作流具体完成了什么事情。
---
This PR fine-tunes the `description` of `summary_workflow` to enable Eko to summarize the specific tasks completed by this workflow.
=> fix: the description of `summary_workflow`

src/extension/tools/browser_use.ts
这个 PR 给 `screenshot_extract_element` 工具添加了很多日志，方便进一步定位问题。
---
This PR adds numerous logs to the `screenshot_extract_element` tool to facilitate further issue location.
=> Fix: log `screenshot_extract_element`

src/models/action.ts
optimize system prompt to solve time problem
case：在GitHub上统计PyTorch官方仓库近一年新增issue中关于性能优化的讨论占比
=> fix:  time problem

src/extension/tools/browser.ts, src/extension/tools/browser_use.ts
BrowserUse Tool：Support the browser operation API provided by fellou
=> fellou use browseruse

src/models/action.ts
更新system prompt里TASK COMPLETION的使用规则以确保任务完成。
=> fix: update TASK COMPLETION section of system prompt

src/models/action.ts
更新system prompt 中 HUMAN OPERATE部分的说明，明确登录和验证码处理流程，增加 human_operate 的使用指导步骤。
=> fix: update HUMAN OPERATE section of ststem prompt

src/common/tools/human.ts
这个 PR 调整了 human tools 的一些 prompt 来实现 user-friendly，还调整了 `human_operate`的 description 来让大模型更好地理解工具的使用场景。
=> Fix: human tools prompts

src/extension/tools/tab_management.ts, src/extension/utils.ts
- 移除不必要的窗口创建逻辑
- 统一在当前窗口打开新标签页
=> fix: Remove the logic of creating a new window in `new_tab` in `tab_management`.

src/core/eko.ts, src/models/action.ts, src/types/action.types.ts, src/types/eko.types.ts
这个 PR 实现了通过 RAG 技术增强原始 prompt 的功能，并由此来提高任务执行成功率。
=> feat: RAG-driven eko patchs

package.json, pnpm-lock.yaml, src/common/chrome/proxy.ts, src/common/log.ts, src/common/summarize-workflow.ts, src/common/tools/cancel_workflow.ts, src/common/tools/human.ts, src/core/eko.ts, src/extension/content/index.ts, src/extension/core.ts, src/extension/tools/browser.ts, src/extension/tools/browser_use.ts, src/extension/tools/get_all_tabs.ts, src/extension/tools/open_url.ts, src/extension/tools/tool_returns_screenshot.ts, src/extension/tools/web_search.ts, src/extension/utils.ts, src/models/action.ts, src/models/workflow.ts, src/services/llm/claude-provider.ts, src/services/llm/openai-provider.ts, src/services/workflow/generator.ts, src/types/eko.types.ts, src/types/llm.types.ts, src/utils/execution-logger.ts
这个 PR 用 `tslog` 统一管理了项目中的日志，并提供`logtail`服务，方便线上排查错误。
=> Feat: logging on logtail

package.json, pnpm-lock.yaml, src/core/eko.ts, src/types/eko.types.ts
=> Fix  remove 'logtail' & 'UUID', remove 'LogtailConfig'

src/services/llm/claude-provider.ts, src/services/llm/openai-provider.ts
=> fix: LLM providers

src/models/action.ts
这个 PR 调整了 `userSidePrompt` 的 `description`，使其输出更人性化。
=> fix: optmize 'description' of 'userSidePrompt'

src/core/eko.ts, src/extension/tools/index.ts, src/extension/tools/switch_tab.ts, src/extension/tools/tab_management.ts, src/types/tools.types.ts
- 新增 SwitchTab 工具类，用于切换到指定的 tab- 从 TabManagement 中移除 switch_tab 功能，简化该工具的职责
- 更新相关文件以支持新的工具
- 删除TabManagement new tab
=> fix:优化tab性能

src/extension/utils.ts
=> fix(getTabId): wrong logic about 'fellouTabId'

src/services/workflow/generator.ts
因为在`doGenerateWorkflow`中 LLM 返回的 JSON 经常会有问题，所以这个 PR 给`doGenerateWorkflow`加入了重试机制，当 LLM 能在 3 次机会内生成正确的响应时返回，否则抛出异常。
=> fix(doGenerateWorkflow): retry

src/models/action.ts
这个 PR 简单修改了 LLM Response 的日志等级。
=> fix: log LLM response

src/schemas/workflow.schema.ts
这个 PR 简化了 `workflowSchema`，防止大模型生成出错并节省 token 开销。
=> fix: simplify 'workflowSchema'

src/core/eko.ts, src/extension/tools/browser_action.ts, src/extension/tools/index.ts, src/extension/tools/open_url.ts, src/extension/tools/tool_returns_screenshot.ts, src/nodejs/tools/browser_use.ts, src/services/workflow/generator.ts, src/types/tools.types.ts, src/web/tools/browser_use.ts
这个 PR 修改了 `browser_use` 工具的命名。
=> fix: 'browser_use' -> 'browser_action'

src/common/log.ts, src/core/eko.ts, src/extension/tools/tab_management.ts, src/extension/utils.ts, src/models/action.ts, src/types/tools.types.ts
这个 PR 主要修复了 `tab_management` 工具存在的一些 bug。
=> Fix: `tab_management`

src/core/eko.ts, src/services/llm/claude-provider.ts, src/services/llm/openai-provider.ts, src/types/eko.types.ts
这个 PR 给 Eko 类新增了一个方法，让应用层更容易获取 log uuid。
=> Feat: `Eko.getLoggerInstaceUUID`

src/models/action.ts
这个 PR 调整了 system prompt 的 human operate 部分，命令大模型在一些关键操作前向人类确认。
=> fix(SP): add key actions description for 'human_operate'
