rollup.config.js
src/extension/tools/index.ts
src/nodejs/tools/index.ts
src/services/workflow/generator.ts
src/types/tools.types.ts
src/universal_tools/cancel_workflow.ts
src/universal_tools/index.ts

这个 PR 增加了一个 `cancel_workflow` 的工具，并强制在每个 SubTask 都添加这个工具，这样 Eko 在遇到工具运行失败时会自动调用这个工具来结束工作流。这可以通过以下方法验证：
1. 在 `web_search` 工具中加入一行代码，让其在执行的时候会抛出一个异常；
2. 编译成浏览器插件，然后运行这个 prompt `Search Sam Altman's information and summarize it into markdown format for export`；
3. 观察 Popup 的日志；
4. 期望行为是 Eko 在尝试几次调用工具失败后会调用`cancel_workflow`工具来取消工作流。
对于工具调用之外的异常，经过测试发现目前的实现可以实现需求所描述的快速失败。
---
This PR introduces a `cancel_workflow` tool and enforces its addition to every SubTask. This allows the Eko to automatically invoke this tool to terminate the workflow when a tool fails to run. This can be verified through the following steps:
1. Add a line of code to the `web_search` tool to cause it to throw an exception during execution.
2. Compile it into a browser extension, and then run the prompt "Search Sam …

feat: add `cancel_workflow` tool

---

rollup.config.js
src/models/action.ts
src/services/workflow/generator.ts
src/services/workflow/templates.ts
src/types/tools.types.ts
src/types/workflow.types.ts
src/universal_tools/human.ts
src/universal_tools/index.ts

这个 PR 增加了与用户交互的工具，它的原理是这样的：当大模型遇到一些他不能独自处理的问题（比如用户提供的 prompt 不够明确、网页需要登录等）时，Eko 会调用这些工具，来让用户和大模型互动，或者从 Eko 中获取对浏览器的控制权。
为了做到这一点，我提供了 4 个 tool：
1. `human_input_text`：大模型向用户询问一个问题，用户提供一个回答；
2. `human_input_single_choice`：大模型向用户询问一个问题，同时给出若干选项，用户从中选择一个；
3. `human_input_multiple_choice`: 大模型向用户询问一个问题，同时给出若干选项，用户从中选择一个或多个；
4. `human_operate`：大模型决定移交控制权，向用户提供一个理由，用户操作完毕后说明自己刚刚的操作。
为了让这些工具更好地发挥作用，我还做了其他修改：
1. 修改了两处 system prompt 来让模型知道 human tools 的意义；
2. 在每个 SubTask 中强制加入`human_input_text`和`human_operate`工具；
3. 同样地，在`WorkflowCallback`接口中新增两个必须提供的回调函数。
你可以通过以下步骤来测试`human_input_text`：
1. 在 [eko-browser-extension-template](https://github.com/FellouAI/eko-browser-extension-template) 的 `src/background/first_workflow.ts`文件中添加两个必需的回调函数：
```ts
onHumanInputText: async (question: string) => { …
```

feature: human tools

---

src/models/action.ts
src/services/workflow/generator.ts
src/services/workflow/templates.ts
src/types/tools.types.ts
src/types/workflow.types.ts
src/universal_tools/index.ts
src/universal_tools/summary_workflow.ts

这个 PR 让 Eko 在工作流的最后生成对工作流的总结，具体修改如下：
1. 新增了`summary_workflow`工具；
2. 修改了 system prompt，让 Eko 在适时生成一个 SubTask 来总结工作流；
3. 新增了`onSummaryWorkflow`的回调函数。
这可以通过以下方式验证：
1. 在 [eko-browser-extension-template](https://github.com/FellouAI/eko-browser-extension-template) 的 `src/background/first_workflow.ts` 文件中添加回调函数：
```typescript
onSummaryWorkflow: async (summary: string) => {
printLog("Summary: " + summary);
},
```
2. 编译并加载浏览器插件；
3. 输入 prompt `Search Sam Altman's information and summarize it into markdown format for export`；
4. 打开插件窗口和 Popup；
5. 期望行为是插件窗口打印对工作流的总结，Popup 控制台打印日志 "summary: ..."；
此外，这个 PR 还做了以下工作：
1. 在生成工作流时，调换了验证工具和强制加入工具的顺序；
2. 在`src/models/action.ts`中，修复了`result`类型未定义可能引起的错误。
---
This PR enables Eko to generate a summary of the workflow at the end of the workflow. The specific …

Feature: workflow summary

---

src/extension/tools/export_file.ts

这个pr修复了使用浏览器插件导出文件时的错误：如果焦点窗口不在浏览器页面上，`getTabId` 会抛出错误，导致导出失败。  
为此，已将 `getTabId` 移入try-catch中，以确保在无法获取浏览器页面时，自动打开一个新页面以完成文件导出。
检验方法：编译并加载浏览器插件，运行含有**导出文件**指示的prompt。
期望行为是如果焦点窗口不在浏览器界面上，插件应自动打开一个新页面并顺利完成文件导出。
----
Fixed an issue with file export using the browser extension: If the focused window is not on the browser page, `getTabId` would throw an error, causing the export to fail.  
To address this, `getTabId` has been moved into a try-catch block to ensure that if the browser page cannot be found, a new page will be opened to complete the file export.
Testing Method:
Compile and load the browser extension. Enter a prompt that includes **file export** and execute it.
Expected Behavior:
If the focused window is not on the browser interface, the extension should automatically open a new …

fix: no valid tab when export file

---

src/core/eko.ts
src/extension/tools/export_file.ts
src/extension/tools/web_search.ts
src/models/workflow.ts
src/services/parser/workflow-parser.ts
src/services/workflow/generator.ts
src/types/action.types.ts
src/types/eko.types.ts
src/types/llm.types.ts
test/integration/workflow.execution.test.ts
test/unit/workflow.test.ts

这个 PR 新增了 `workingWindowId` 作为 Eko 工作流执行时的环境。这个 PR 做了以下修改：
1. 把`EkoConfig`重构为`LLMConfig`;
2. 新增`EkoConfig`接口，包含一个`workingWindowId?: number`作为属性；
3. 在`ExecutionContext`接口新增一个`ekoConfig`属性；
4. 在`Eko`类的构造函数、工作流的生成和修改的方法等必要的地方新增了`ekoConfig`参数；
5. 修改了`web_search`和`export_file`在打开新窗口时的逻辑：如果`context.ekoConfig.workingWindowId`存在值时不打开新窗口，而是在指定的窗口执行动作；否则和往常一样执行。
你可以通过将`workingWindowId`设置为已经打开的浏览器窗口的 ID 来验证这个 PR，期望行为是`web_search`和`export_file`工具将不会打开新窗口。
---
This PR adds `workingWindowId` as an environment variable for Eko workflow execution. The following changes have been made in this PR:
1. Refactored `EkoConfig` to `LLMConfig`;
2. Added a new `EkoConfig` interface, which includes a property `workingWindowId?: number`;
3. Added an `ekoConfig` property to the `ExecutionContext` interface;
4. Added …

Feature: working window ID

---

src/extension/tools/export_file.ts
src/types/workflow.types.ts
src/web/tools/export_file.ts

这个 PR 对 extension 和 web 环境下的 `export_file` 工具添加了可选的回调函数。
---
This PR adds an optional callback function to the `export_file` tool in both extension and web environments.

Feature: add a callback when `export_file`

---

src/universal_tools/human.ts

这个 PR 修复了以下问题：当 human tools 接收到用户提供的空回答（即`""`）时会认为没有实现相关的 callback，导致后续 Eko 执行失败。
你可以通过以下方式验证这个 PR：
1. 调用 human tools 时提供非空回答，期望行为是工具会正常返回用户的回答；
2. 调用 human tools 时故意提供空的回答，期望行为是工具 _不会_ 返回`status="Error: Cannot get user's answer."`的结果；
3. 不实现相关的 callback，再调用 human tools，期望行为是工具 _会_ 返回`status="Error: Cannot get user's answer."`的结果。
---
This PR fixes the following issue: When human tools receive a `""` response from the user, it incorrectly assumes that the relevant callback has not been implemented, leading to subsequent Eko execution failures.
You can verify this PR by following these steps:
1. Provide a non-empty response when calling human tools. The expected behavior is that the tool will normally return the user's response.
2. Deliberately provide an empty response when calling human …

Fix: human tools empty answer

---

src/utils/execution-logger.ts

这个 PR 修复了 `logError()` 方法中一个潜在的问题：参数`error`可能无法读取`message`字段，进而导致错误无法被记录下来。在实际使用过程中已经多次触发这个错误（需要补充日志）。
对此我的修复方法是给这个逻辑套上 try-catch，尝试捕获并记录这个错误，同时在方法的入口就在控制台打印这个错误，以免因为这个方法的错误实现导致其他错误无法被记录下来。
---
This PR fixes a potential issue in the `logError()` method: the parameter `error` may not be able to read the `message` field, which could subsequently prevent the error from being logged. This error has been triggered multiple times in actual usage (additional logging is needed).
My fix for this is to encapsulate this logic within a try-catch block to attempt to catch and log this error. At the same time, I will print the error to the console at the entrance of the method to prevent other errors from not being logged due to the faulty implementation of this method.

fix: may missing fields when calling `logError`

---

src/universal_tools/human.ts

这个 PR 对`human_operate`工具的`description`字段补充了一些说明，强调它在做一些危险操作时需要询问用户意见。
---
This PR adds some text to the `description` field of the `human_operate` tool, emphasizing the need to ask for user consent when performing dangerous operations.

fix: add confirmations in `human_operate` description

---

src/core/eko.ts
src/models/action.ts
src/models/workflow.ts
src/services/workflow/generator.ts
src/services/workflow/templates.ts
src/types/eko.types.ts
src/types/tools.types.ts
src/types/workflow.types.ts
src/universal_tools/document_agent.ts
src/universal_tools/index.ts
src/universal_tools/summary_workflow.ts
src/universal_tools/write_context.ts

**注意：这个 PR 修改了 `Eko.execute` 的签名，请下游调用者注意适配。**
这个 PR 增加了 Workflow Result 的功能，让工作流结束时返回一个结果，包括以下字段：
1. `isSuccessful`：指示工作流最终是否执行成功；
2. `summary`：对工作流本身的简短的总结；
3. `payload`：工作流的产物，目前支持纯文本产物，同时预留了其他格式产物的类型，当工作流需要返回结果时（例如“给我生成一个述职报告”）非空，当工作流不需要返回结果时（例如“帮我打开 OpenAI 的官网”）为空，
以下是实现思路：
1. 新增`WorkflowResult`类型，涵盖以上字段；
2. 新增`DocumentAgentToolInput`工具，让它实现文书 Agent 工作，负责生成纯文本产物，通过修改工具的 `description` 来提示模型在合适的时候调用；
3. 修改`SummaryWorkflow`工具，新增输入参数`isSuccessful`，并微调 prompt；
4. 新增关于`context.variables`的写入逻辑：`DocumentAgentToolInput`工具会把返回值写入`workflow_transcript`键中，`SummaryWorkflow`工具会把返回值写入`workflow_is_successful`和`workflow_summary`中；
5. 新增关于`context.variables`的读取逻辑：`WorkflowImpl.execute`方法会读取`workflow_is_successful`, `workflow_summary`, `workflow_transcript`的值并组装成`WorkflowResult`类型的值。
以下是主要的修改：
1. …

feat: add `WorkflowResult`

---

rollup.config.js
src/core/eko.ts

这个 PR 让 `Eko.constructor` 执行时使用`git rev-parse HEAD`命令打印当前的 commit hash，方便后续调试。
---
This PR enables the `Eko.constructor` to print the current commit hash using the `git rev-parse HEAD` command when executed, facilitating subsequent debugging.

Feature: log commit hash

---

src/extension/utils.ts
src/services/workflow/generator.ts

这个 PR 做了以下修改：
1. 在`getWindowId`中新增对`window.FELLOU_WINDOW_ID`的支持，并添加了一条警告日志；
2. 修改了 Workflow Summary 子任务的 description，让其必须使用`summary_workflow`工具。
---
The following changes have been made in this PR:
1. Added support for `window.FELLOU_WINDOW_ID` in `getWindowId` and included a warning log.
2. Modified the description of the Workflow Summary subtask to require the use of the `summary_workflow` tool.

Some small fixes

---

src/core/eko.ts
src/types/eko.types.ts

这个 PR 修复了以下情况：当下游调用者在调用 `Eko.constructor` 时仅提供了一部分 `ekoConfig`（例如`{ callback: hookLogs() }`），`chrome`的值将会是 `undefined`，期望的值为`chrome`。
---
This PR fixes the following scenario: When a downstream caller provides only a partial `ekoConfig` (e.g., `{ callback: hookLogs() }`) when invoking `Eko.constructor`, the value of `chrome` will be `undefined`, whereas the expected value is `chrome`.

fix: wrong configure logic about `EkoConfig`

---

src/core/eko.ts

这个 PR 修复了`buildEkoConfig`的错误的函数签名，现在要求调用方必须提供 `ekoConfig` 参数。
---
This PR fixes the incorrect function signature of `buildEkoConfig`, and now requires the caller to provide the `ekoConfig` parameter.

fix: the wrong signature in `buildEkoConfig`

---

src/extension/tools/browser_use.ts
src/extension/utils.ts

这个 PR 尝试修复在执行 `getTabId` 函数时出现的 "Could not find a valid tab" 报错。这个 PR 做了以下修改：
1. 将`getTabId`函数中获取`windowId`的方式从`let windowId = context.variables.get('windowId') as any;`修改为`let windowId = await getWindowId(context);`；
2. 修改了`getCurrentTabId`的实现，现在它不再返回不期望的`undefined`了；
3. 添加了很多日志。
这个 PR 的验证需要很多“在当前标签页操作”的用例（例如“点开这个页面的第一个链接”）。
---
This PR attempts to fix the "Could not find a valid tab" error that occurs when executing the `getTabId` function. The following changes have been made in this PR:
1. The method of obtaining `windowId` in the `getTabId` function has been changed from `let windowId = context.variables.get('windowId') as any;` to `let windowId = await getWindowId(context);`.
2. The implementation of `getCurrentTabId` has been modified so that it no longer returns the undesired …

Fix: `getWindowId` and `getTabId`

---

src/extension/tools/web_search.ts

这个 PR 修复了 `web_search` 工具的 `input_shema` 的一个问题，即缺少`url`参数。此外还设置了默认的搜索引擎为 Bing，以便不方便访问 Google 的用户也能轻松运行 `web_search` 工具。
---
This PR fixes an issue with the `input_schema` of the `web_search` tool, which was missing the `url` parameter. Additionally, it sets the default search engine to Bing, making it easier for users who have difficulty accessing Google to run the `web_search` tool.

fix: add `url` to input_shema of `web_search`

---

src/extension/tools/browser_use.ts

更新 input_text 的prompt 明确搜索任务需要使用enter键的要求

fix: descriptions of input_text in browser_use

---

src/models/action.ts
src/schemas/workflow.schema.ts
src/services/workflow/templates.ts

- 在 workflow/templates.ts 中修改了 generate_workflow 的描述，去除了对节点数量的限制
- 在 workflow.schema.ts 中调整了 thinking 字段的描述，将输出字数限制从 20增加到 50

Fix: Update Workflow Descriptions: Remove Node Limit & Increase Thinking Field Character Limit

---

src/common/summarize-workflow.ts
src/models/action.ts

这个 PR 修复了以下问题：某些情况下工作流已经执行成功了，但是 summarize workflow 会因为上下文缺失/过长而返回 `isSuccessful=false`。我修改了 `return_output` 工具的入参，并在两个工具间强制同步`__isSuccessful__`变量来避免二者在这个问题上给出不同意见。

Fix: summarize workflow

---

src/models/action.ts
src/types/workflow.types.ts

这个 PR 给 `onLlmMessageUserSidePrompt` 回调函数增加了 `toolName` 参数。现在这个回调函数会同时提供大模型写的 userSidePrompt 和工具的名称。

fix: add tool name to `onLlmMessageUserSidePrompt`

---

src/services/llm/openai-provider.ts

`document_agent` 工具调用了 LLM API，且没有提供 `tools` 参数，导致 API 报错：
```
{
"error": {
"message": "Invalid value for 'parallel_tool_calls': 'parallel_tool_calls' is only allowed when 'tools' are specified.",
"type": "invalid_request_error",
"param": "parallel_tool_calls",
"code": null
}
}
```
这个 PR 修复了这个问题，在传参时检查 `tools` 参数是否为空来决定 `parallel_tool_calls` 的值。
你可以通过以下方式来验证这个 PR：构造一个 prompt，让 Eko 使用 `document_agent` 工具，例如：`use 'document_agent' tool to write a fairy tale and output it directly`。

Fix: 'parallel_tool_calls' is only allowed when 'tools' are specified.

---

src/models/action.ts

这个 PR 将 `return_output` 工具设置为必选参数，修复了 https://github.com/FellouAI/eko/pull/115 的错误。

fix: set 'isSuccessful' as required

---

src/models/action.ts

考虑到不同的大模型在”工具调用前的文本回复（思考）“这个功能细节上不一致，这个 PR 通过增加 `thinking` 字段来强制大模型输出思考内容。

feat: enforce the thinking content of the LLM

---

src/extension/tools/browser_use.ts
src/extension/tools/tool_returns_screenshot.ts

这个 PR 增加了一些等待函数：
* 在标签页创建后`sleep(3000)`以便页面加载完成
* 在截图的标记移除前`sleep(500)`以便调试时方便查看截图的标记

feat: add some sleep()

---

src/models/action.ts

- 新增 evaluate_previous_goal 字段，用于评估上一个目标或操作的成功情况- 新增 memory 字段，用于记录已完成的操作和需要记住的信息- 新增 next_goal 字段，用于描述下一个即时操作需要完成的任务

feat:add check feature

---

src/models/action.ts

这个 PR 优化了在工作流执行前获取已存在标签页的逻辑，防止脏数据污染。

fix: get 'existingTabs' before workflow running

---

src/extension/utils.ts

这个 PR 修复了 `getCurrentTabId` 中的一个疏漏。

fix(getCurrentTabId): use 'chromeProxy'

---

src/common/log.ts

fix(transportFormatted): log 'logErrors' in more readable way

---

src/extension/utils.ts

这个 PR 修改了 `getWindowId` 的实现，把`context.ekoConfig.workingWindowId`作为之前实现全部失败时最后的垫底值。

fix(getWindowId): add 'context.ekoConfig.workingWindowId' as fallback

---

packages/eko-core/src/agent/browser/browser_labels.ts

The child nodes in the shadow DOM root in the web component cannot trigger the click event

support browser shadow dom element click trigger

---

packages/eko-core/src/agent/browser/build_dom_tree.ts

在shadow dom 内的子元素，只需要可交互的、可见的判断，不需要isTopElement也认为是可高亮的吧，不然目前shadow dom root内的子元素都无法被识别到

[build_dom_tree.ts]  For Shadow DOM elements, use more lenient criteria
